# Generated by Django 5.0.2 on 2024-05-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsDetector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.BigIntegerField()),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
